import type { ProgramTemplate } from '../types';

export const firefighter_hybrid_6week: ProgramTemplate = {
  id: 'firefighter_hybrid_6week',
  name: 'Firefighter Hybrid Training (6-Week)',
  durationWeeks: 6,
  daysPerWeek: 4,
  description: 'Progressive hybrid program combining strength, conditioning, and work capacity for operational readiness. Perfect for firefighters and tactical athletes.',
  days: [
    // WEEK 1
    {
      week: 1,
      day: 1,
      title: 'Strength Foundation',
      priority: 1,
      type: 'training',
      phase: 'Volume',
      warmup: [
        { id: 'arm_circle', sets: 2, repsOrDuration: '10 each direction', rpe: 3 },
        { id: 'bodyweight_squat', sets: 2, repsOrDuration: '15 reps', rpe: 4 },
        { id: 'glute_bridge', sets: 2, repsOrDuration: '15 reps', rpe: 4 },
      ],
      exercises: [
        {
          id: 'goblet_squat',
          sets: 3,
          repsOrDuration: '12 reps',
          rpe: 7,
          tags: ['legs', 'functional'],
          replacements: ['bodyweight_squat', 'db_squat'],
        },
        {
          id: 'push_up',
          sets: 3,
          repsOrDuration: '10-15 reps',
          rpe: 7,
          tags: ['push', 'bodyweight'],
          replacements: ['knee_push_up', 'incline_push_up'],
        },
        {
          id: 'bent_over_row',
          sets: 3,
          repsOrDuration: '12 reps',
          rpe: 7,
          tags: ['pull', 'back'],
          replacements: ['inverted_row', 'resistance_band_row'],
        },
        {
          id: 'plank',
          sets: 3,
          repsOrDuration: '30-45 sec',
          rpe: 6,
          tags: ['core', 'stability'],
          replacements: ['modified_plank', 'wall_sit'],
        },
        {
          id: 'farmer_walk',
          sets: 3,
          repsOrDuration: '30 sec',
          rpe: 7,
          tags: ['carry', 'functional'],
          replacements: ['suitcase_carry', 'overhead_carry'],
        },
      ],
      cooldown: [
        { id: 'walking', sets: 1, repsOrDuration: '5 min easy pace', rpe: 3 },
        { id: 'child_pose_stretch', sets: 1, repsOrDuration: '1 min', rpe: 2 },
        { id: 'hip_flexor_stretch', sets: 1, repsOrDuration: '1 min each leg', rpe: 2 },
      ],
    },
    {
      week: 1,
      day: 2,
      title: 'Conditioning Base',
      priority: 2,
      type: 'training',
      phase: 'Volume',
      warmup: [
        { id: 'jumping_jacks', sets: 2, repsOrDuration: '30 sec', rpe: 4 },
        { id: 'high_knees', sets: 2, repsOrDuration: '20 sec', rpe: 4 },
        { id: 'butt_kicks', sets: 2, repsOrDuration: '20 sec', rpe: 4 },
      ],
      exercises: [
        {
          id: 'rowing_machine',
          sets: 4,
          repsOrDuration: '2 min work, 1 min rest',
          rpe: 6,
          tags: ['cardio', 'full_body'],
          replacements: ['stationary_bike', 'elliptical'],
        },
        {
          id: 'mountain_climbers',
          sets: 3,
          repsOrDuration: '30 sec',
          rpe: 7,
          tags: ['cardio', 'core'],
          replacements: ['high_knees_in_place', 'bicycle_crunches'],
        },
        {
          id: 'kettlebell_swing',
          sets: 3,
          repsOrDuration: '20 reps',
          rpe: 7,
          tags: ['power', 'hinge'],
          replacements: ['deadlift', 'good_morning'],
        },
        {
          id: 'burpees',
          sets: 3,
          repsOrDuration: '8-12 reps',
          rpe: 8,
          tags: ['cardio', 'full_body'],
          replacements: ['squat_thrust', 'modified_burpee'],
        },
      ],
      cooldown: [
        { id: 'walking', sets: 1, repsOrDuration: '10 min slow pace', rpe: 3 },
        { id: 'quad_stretch', sets: 1, repsOrDuration: '1 min each leg', rpe: 2 },
        { id: 'calf_stretch', sets: 1, repsOrDuration: '1 min each leg', rpe: 2 },
      ],
    },
    {
      week: 1,
      day: 3,
      title: 'Functional Strength',
      priority: 3,
      type: 'training',
      phase: 'Strength',
      warmup: [
        { id: 'arm_swings', sets: 2, repsOrDuration: '10 each direction', rpe: 3 },
        { id: 'leg_swings', sets: 2, repsOrDuration: '10 each leg', rpe: 3 },
        { id: 'torso_twist', sets: 2, repsOrDuration: '10 each direction', rpe: 3 },
      ],
      exercises: [
        {
          id: 'deadlift',
          sets: 4,
          repsOrDuration: '8 reps',
          rpe: 7,
          tags: ['hinge', 'posterior'],
          replacements: ['romanian_deadlift', 'sumo_deadlift'],
        },
        {
          id: 'overhead_press',
          sets: 3,
          repsOrDuration: '10 reps',
          rpe: 7,
          tags: ['push', 'vertical'],
          replacements: ['dumbbell_press', 'push_press'],
        },
        {
          id: 'pull_up',
          sets: 3,
          repsOrDuration: '5-10 reps',
          rpe: 8,
          tags: ['pull', 'vertical'],
          replacements: ['assisted_pull_up', 'lat_pulldown'],
        },
        {
          id: 'single_leg_glute_bridge',
          sets: 3,
          repsOrDuration: '8 each leg',
          rpe: 6,
          tags: ['unilateral', 'glutes'],
          replacements: ['glute_bridge', 'clamshells'],
        },
        {
          id: 'side_plank',
          sets: 2,
          repsOrDuration: '20-30 sec each side',
          rpe: 6,
          tags: ['core', 'lateral'],
          replacements: ['modified_side_plank', 'lateral_raises'],
        },
      ],
      cooldown: [
        { id: 'walking', sets: 1, repsOrDuration: '5 min', rpe: 3 },
        { id: 'pigeon_pose', sets: 1, repsOrDuration: '1 min each side', rpe: 2 },
        { id: 'seated_spinal_twist', sets: 1, repsOrDuration: '1 min each side', rpe: 2 },
      ],
    },
    {
      week: 1,
      day: 4,
      title: 'Work Capacity',
      priority: 4,
      type: 'training',
      phase: 'Volume',
      warmup: [
        { id: 'light_jogging', sets: 1, repsOrDuration: '5 min', rpe: 4 },
        { id: 'dynamic_stretching', sets: 1, repsOrDuration: '5 min', rpe: 3 },
      ],
      exercises: [
        {
          id: 'circuit_training',
          sets: 3,
          repsOrDuration: '12 min (4 exercises x 3 rounds)',
          rpe: 7,
          tags: ['circuit', 'metabolic'],
          replacements: ['interval_training', 'fartlek'],
        },
        {
          id: 'battle_ropes',
          sets: 3,
          repsOrDuration: '30 sec work, 30 sec rest',
          rpe: 8,
          tags: ['cardio', 'arms'],
          replacements: ['jumping_jacks', 'high_intensity_cycling'],
        },
        {
          id: 'box_step_ups',
          sets: 3,
          repsOrDuration: '45 sec',
          rpe: 6,
          tags: ['legs', 'cardio'],
          replacements: ['step_ups', 'stair_climbing'],
        },
        {
          id: 'medicine_ball_slam',
          sets: 3,
          repsOrDuration: '15 reps',
          rpe: 8,
          tags: ['power', 'core'],
          replacements: ['wood_chops', 'sledgehammer_swings'],
        },
      ],
      cooldown: [
        { id: 'walking', sets: 1, repsOrDuration: '10 min', rpe: 3 },
        { id: 'full_body_stretch_routine', sets: 1, repsOrDuration: '10 min', rpe: 2 },
      ],
    },

    // WEEK 2 - Progression
    {
      week: 2,
      day: 1,
      title: 'Strength Progression',
      priority: 1,
      type: 'training',
      phase: 'Strength',
      warmup: [
        { id: 'arm_circle', sets: 2, repsOrDuration: '10 each direction', rpe: 3 },
        { id: 'bodyweight_squat', sets: 2, repsOrDuration: '20 reps', rpe: 4 },
        { id: 'glute_bridge', sets: 2, repsOrDuration: '20 reps', rpe: 4 },
      ],
      exercises: [
        {
          id: 'goblet_squat',
          sets: 4,
          repsOrDuration: '15 reps',
          rpe: 7,
          tags: ['legs', 'functional'],
          replacements: ['barbell_squat', 'front_squat'],
        },
        {
          id: 'push_up',
          sets: 4,
          repsOrDuration: '12-18 reps',
          rpe: 7,
          tags: ['push', 'bodyweight'],
          replacements: ['diamond_push_up', 'decline_push_up'],
        },
        {
          id: 'bent_over_row',
          sets: 4,
          repsOrDuration: '15 reps',
          rpe: 7,
          tags: ['pull', 'back'],
          replacements: ['t_bar_row', 'cable_row'],
        },
        {
          id: 'plank',
          sets: 3,
          repsOrDuration: '45-60 sec',
          rpe: 7,
          tags: ['core', 'stability'],
          replacements: ['plank_up_downs', 'bird_dog'],
        },
        {
          id: 'farmer_walk',
          sets: 4,
          repsOrDuration: '45 sec',
          rpe: 7,
          tags: ['carry', 'functional'],
          replacements: ['suitcase_carry', 'overhead_carry'],
        },
      ],
      cooldown: [
        { id: 'walking', sets: 1, repsOrDuration: '5 min easy pace', rpe: 3 },
        { id: 'child_pose_stretch', sets: 1, repsOrDuration: '1 min', rpe: 2 },
        { id: 'hip_flexor_stretch', sets: 1, repsOrDuration: '1 min each leg', rpe: 2 },
      ],
    },

    // WEEK 3 - Strength & Power Development
    {
      week: 3,
      day: 1,
      title: 'Power & Explosiveness',
      priority: 1,
      type: 'training',
      phase: 'Strength',
      warmup: [
        { id: 'dynamic_warmup', sets: 1, repsOrDuration: '8 min', rpe: 4 },
        { id: 'activation_exercises', sets: 1, repsOrDuration: '5 min', rpe: 4 },
      ],
      exercises: [
        {
          id: 'box_jump',
          sets: 4,
          repsOrDuration: '5 reps',
          rpe: 8,
          tags: ['power', 'plyometric', 'firefighter'],
          replacements: ['step_up_explosive', 'jump_squat'],
        },
        {
          id: 'deadlift_moderate',
          sets: 4,
          repsOrDuration: '6-8 reps',
          rpe: 8,
          tags: ['strength', 'posterior_chain'],
          replacements: ['trap_bar_deadlift', 'sumo_deadlift'],
        },
        {
          id: 'overhead_press',
          sets: 4,
          repsOrDuration: '6-8 reps',
          rpe: 7,
          tags: ['push', 'functional'],
          replacements: ['dumbbell_press', 'push_press'],
        },
        {
          id: 'weighted_pull_up',
          sets: 3,
          repsOrDuration: '5-8 reps',
          rpe: 8,
          tags: ['pull', 'strength'],
          replacements: ['assisted_pull_up', 'lat_pulldown_heavy'],
        },
        {
          id: 'sandbag_carry',
          sets: 3,
          repsOrDuration: '40 yards',
          rpe: 7,
          tags: ['carry', 'functional', 'firefighter'],
          replacements: ['farmer_walk_heavy', 'dumbbell_carry'],
        },
      ],
      cooldown: [
        { id: 'walking', sets: 1, repsOrDuration: '5 min', rpe: 3 },
        { id: 'stretching', sets: 1, repsOrDuration: '10 min', rpe: 2 },
      ],
    },
    {
      week: 3,
      day: 2,
      title: 'Work Capacity Challenge',
      priority: 2,
      type: 'training',
      phase: 'Strength',
      warmup: [
        { id: 'light_jog', sets: 1, repsOrDuration: '5 min', rpe: 4 },
        { id: 'movement_prep', sets: 1, repsOrDuration: '5 min', rpe: 3 },
      ],
      exercises: [
        {
          id: 'e3a5b94933474fd3b9156f0fe030e3ee', // Burpees (verified real ID)
          sets: 4,
          repsOrDuration: '8 min AMRAP: 5 burpees, 10 squats, 15 push-ups',
          rpe: 8,
          tags: ['circuit', 'conditioning', 'firefighter'],
          replacements: ['3d05fd6ffbb64691b892b13cdc6d98ff', '9b5bdbf6f49e478e8444c4a8616a594e'], // Mountain Climbers, Bodyweight Squat
        },
        {
          id: '08290306ba654e349a6660fa9b9c2ac1', // Tire Flip (verified real ID)
          sets: 3,
          repsOrDuration: '8-10 flips',
          rpe: 8,
          tags: ['functional', 'power', 'firefighter'],
          replacements: ['25aef4fb46f74fabb92c69334cc7edc4', 'b07d4b7db5fc429285e1e99bcfadf28e'], // Broad Jumps, Superman Hold
        },
        {
          id: '6544f999050d4eaa9de64d3d1fe43ffc', // High Knees (verified real ID)
          sets: 3,
          repsOrDuration: '45 sec',
          rpe: 8,
          tags: ['cardio', 'coordination'],
          replacements: ['3d05fd6ffbb64691b892b13cdc6d98ff', '2da1345993f947bc858c50e3f09563c1'], // Mountain Climbers, Flutter Kicks
        },
        {
          id: '09f4a00ba8594ee9bdc4c7a7dd1934d3', // Step-Ups (verified real ID)
          sets: 3,
          repsOrDuration: '3 flights worth',
          rpe: 8,
          tags: ['cardio', 'functional', 'firefighter'],
          replacements: ['9b5bdbf6f49e478e8444c4a8616a594e', '2227e83231e640e79270d5f86cb15c2f'], // Bodyweight Squat, Jump Squats
        },
      ],
      cooldown: [
        { id: 'cool_down_walk', sets: 1, repsOrDuration: '8 min', rpe: 3 },
        { id: 'recovery_stretching', sets: 1, repsOrDuration: '12 min', rpe: 2 },
      ],
    },
    {
      week: 3,
      day: 3,
      title: 'Strength Endurance',
      priority: 3,
      type: 'training',
      phase: 'Strength',
      warmup: [
        { id: 'rowing_warmup', sets: 1, repsOrDuration: '5 min', rpe: 4 },
        { id: 'mobility_flow', sets: 1, repsOrDuration: '5 min', rpe: 3 },
      ],
      exercises: [
        {
          id: 'squat_moderate',
          sets: 4,
          repsOrDuration: '12-15 reps',
          rpe: 7,
          tags: ['legs', 'endurance'],
          replacements: ['goblet_squat_heavy', 'front_squat'],
        },
        {
          id: 'bench_press_moderate',
          sets: 4,
          repsOrDuration: '10-12 reps',
          rpe: 7,
          tags: ['push', 'chest'],
          replacements: ['dumbbell_press', 'push_up_weighted'],
        },
        {
          id: 'rowing_machine',
          sets: 4,
          repsOrDuration: '500m intervals',
          rpe: 7,
          tags: ['cardio', 'pull'],
          replacements: ['cable_row', 'bent_over_row'],
        },
        {
          id: 'plank_variations',
          sets: 3,
          repsOrDuration: '90 sec',
          rpe: 7,
          tags: ['core', 'isometric'],
          replacements: ['ab_circuit', 'dead_bug'],
        },
      ],
      cooldown: [
        { id: 'easy_bike', sets: 1, repsOrDuration: '10 min', rpe: 3 },
        { id: 'full_body_stretch', sets: 1, repsOrDuration: '15 min', rpe: 2 },
      ],
    },

    // WEEK 4 - Tactical Integration
    {
      week: 4,
      day: 1,
      title: 'Tactical Movements',
      priority: 1,
      type: 'training',
      phase: 'Strength',
      warmup: [
        { id: 'tactical_warmup', sets: 1, repsOrDuration: '10 min', rpe: 4 },
        { id: 'gear_simulation_light', sets: 1, repsOrDuration: '5 min', rpe: 4 },
      ],
      exercises: [
        {
          id: 'hose_drag_simulation',
          sets: 4,
          repsOrDuration: '50 yards',
          rpe: 8,
          tags: ['functional', 'drag', 'firefighter'],
          replacements: ['sled_drag', 'rope_drag'],
        },
        {
          id: 'ladder_raise_simulation',
          sets: 3,
          repsOrDuration: '8-10 reps',
          rpe: 8,
          tags: ['functional', 'overhead', 'firefighter'],
          replacements: ['medicine_ball_throw', 'wall_ball'],
        },
        {
          id: 'rescue_carry',
          sets: 3,
          repsOrDuration: '30 yards',
          rpe: 8,
          tags: ['carry', 'functional', 'firefighter'],
          replacements: ['fireman_carry', 'weighted_carry'],
        },
        {
          id: 'stair_climb_gear',
          sets: 3,
          repsOrDuration: '5 flights',
          rpe: 9,
          tags: ['cardio', 'weighted', 'firefighter'],
          replacements: ['weighted_step_ups', 'stair_master'],
        },
        {
          id: 'ventilation_simulation',
          sets: 3,
          repsOrDuration: '2 min',
          rpe: 8,
          tags: ['functional', 'endurance', 'firefighter'],
          replacements: ['sledgehammer_swings', 'battle_ropes'],
        },
      ],
      cooldown: [
        { id: 'gear_removal_stretch', sets: 1, repsOrDuration: '5 min', rpe: 2 },
        { id: 'tactical_recovery', sets: 1, repsOrDuration: '10 min', rpe: 2 },
      ],
    },
    {
      week: 4,
      day: 2,
      title: 'Emergency Response Prep',
      priority: 2,
      type: 'training',
      phase: 'Strength',
      warmup: [
        { id: 'alarm_response_sim', sets: 1, repsOrDuration: '5 min', rpe: 5 },
        { id: 'dynamic_prep', sets: 1, repsOrDuration: '5 min', rpe: 4 },
      ],
      exercises: [
        {
          id: 'sprint_intervals',
          sets: 6,
          repsOrDuration: '30 sec on, 90 sec off',
          rpe: 9,
          tags: ['speed', 'conditioning', 'firefighter'],
          replacements: ['bike_sprints', 'rowing_sprints'],
        },
        {
          id: 'burpee_variations',
          sets: 4,
          repsOrDuration: '10-15 reps',
          rpe: 8,
          tags: ['full_body', 'explosive'],
          replacements: ['squat_thrust', 'mountain_climbers'],
        },
        {
          id: 'agility_ladder',
          sets: 4,
          repsOrDuration: '2 lengths',
          rpe: 7,
          tags: ['agility', 'coordination'],
          replacements: ['cone_drills', 'lateral_shuffles'],
        },
        {
          id: 'weighted_vest_walk',
          sets: 1,
          repsOrDuration: '15 min',
          rpe: 7,
          tags: ['endurance', 'weighted', 'firefighter'],
          replacements: ['rucking', 'weighted_carry'],
        },
      ],
      cooldown: [
        { id: 'active_recovery_walk', sets: 1, repsOrDuration: '10 min', rpe: 3 },
        { id: 'post_workout_stretch', sets: 1, repsOrDuration: '15 min', rpe: 2 },
      ],
    },
    {
      week: 4,
      day: 3,
      title: 'Recovery & Mobility',
      priority: 3,
      type: 'recovery',
      phase: 'Deload',
      warmup: [
        { id: 'gentle_movement', sets: 1, repsOrDuration: '5 min', rpe: 3 },
      ],
      exercises: [
        {
          id: 'yoga_flow',
          sets: 1,
          repsOrDuration: '30 min',
          rpe: 4,
          tags: ['mobility', 'recovery'],
          replacements: ['stretching_routine', 'tai_chi'],
        },
        {
          id: 'foam_rolling',
          sets: 1,
          repsOrDuration: '15 min',
          rpe: 3,
          tags: ['recovery', 'myofascial'],
          replacements: ['self_massage', 'lacrosse_ball'],
        },
        {
          id: 'breathing_exercises',
          sets: 3,
          repsOrDuration: '5 min',
          rpe: 2,
          tags: ['recovery', 'stress_management'],
          replacements: ['meditation', 'relaxation'],
        },
      ],
      cooldown: [
        { id: 'meditation', sets: 1, repsOrDuration: '10 min', rpe: 1 },
      ],
    },

    // WEEK 5 - Intensity Peak
    {
      week: 5,
      day: 1,
      title: 'Maximum Effort',
      priority: 1,
      type: 'training',
      phase: 'Peak',
      warmup: [
        { id: 'thorough_warmup', sets: 1, repsOrDuration: '12 min', rpe: 5 },
        { id: 'nervous_system_prep', sets: 1, repsOrDuration: '5 min', rpe: 4 },
      ],
      exercises: [
        {
          id: 'deadlift_heavy',
          sets: 5,
          repsOrDuration: '3-5 reps',
          rpe: 9,
          tags: ['strength', 'max_effort'],
          replacements: ['trap_bar_deadlift_heavy', 'rack_pull'],
        },
        {
          id: 'squat_heavy',
          sets: 4,
          repsOrDuration: '4-6 reps',
          rpe: 8,
          tags: ['legs', 'strength'],
          replacements: ['front_squat_heavy', 'box_squat'],
        },
        {
          id: 'weighted_pull_up_heavy',
          sets: 4,
          repsOrDuration: '3-6 reps',
          rpe: 9,
          tags: ['pull', 'max_effort'],
          replacements: ['lat_pulldown_heavy', 'assisted_pull_up_heavy'],
        },
        {
          id: 'farmers_walk_competition',
          sets: 3,
          repsOrDuration: '60 yards',
          rpe: 9,
          tags: ['carry', 'grip', 'firefighter'],
          replacements: ['suitcase_carry', 'trap_bar_carry'],
        },
      ],
      cooldown: [
        { id: 'extended_cooldown', sets: 1, repsOrDuration: '15 min', rpe: 2 },
        { id: 'ice_bath_optional', sets: 1, repsOrDuration: '5 min', rpe: 2 },
      ],
    },
    {
      week: 5,
      day: 2,
      title: 'Competition Prep',
      priority: 2,
      type: 'training',
      phase: 'Peak',
      warmup: [
        { id: 'competition_warmup', sets: 1, repsOrDuration: '10 min', rpe: 5 },
      ],
      exercises: [
        {
          id: 'firefighter_combat_challenge',
          sets: 2,
          repsOrDuration: 'Full course simulation',
          rpe: 9,
          tags: ['competition', 'functional', 'firefighter'],
          replacements: ['obstacle_course', 'functional_circuit'],
        },
        {
          id: 'time_trial_events',
          sets: 3,
          repsOrDuration: 'Various stations',
          rpe: 9,
          tags: ['speed', 'competition', 'firefighter'],
          replacements: ['timed_circuits', 'benchmark_workouts'],
        },
      ],
      cooldown: [
        { id: 'competition_recovery', sets: 1, repsOrDuration: '20 min', rpe: 2 },
      ],
    },
    {
      week: 5,
      day: 3,
      title: 'Active Recovery',
      priority: 3,
      type: 'recovery',
      phase: 'Deload',
      warmup: [
        { id: 'light_movement', sets: 1, repsOrDuration: '5 min', rpe: 3 },
      ],
      exercises: [
        {
          id: 'light_swimming',
          sets: 1,
          repsOrDuration: '30 min',
          rpe: 4,
          tags: ['recovery', 'low_impact'],
          replacements: ['walking', 'easy_bike'],
        },
        {
          id: 'mobility_session',
          sets: 1,
          repsOrDuration: '20 min',
          rpe: 3,
          tags: ['mobility', 'recovery'],
          replacements: ['stretching', 'yoga'],
        },
      ],
      cooldown: [
        { id: 'relaxation', sets: 1, repsOrDuration: '15 min', rpe: 1 },
      ],
    },

    // WEEK 6 - PEAK WEEK (Example of final week)
    {
      week: 6,
      day: 1,
      title: 'Peak Strength + Power',
      priority: 1,
      type: 'training',
      phase: 'Peak',
      warmup: [
        { id: 'dynamic_warm_up', sets: 1, repsOrDuration: '10 min', rpe: 4 },
        { id: 'activation_exercises', sets: 2, repsOrDuration: '8-10 reps each', rpe: 5 },
      ],
      exercises: [
        {
          id: 'barbell_squat',
          sets: 4,
          repsOrDuration: '5 reps',
          rpe: 8,
          tags: ['legs', 'strength'],
          replacements: ['front_squat', 'goblet_squat'],
        },
        {
          id: 'bench_press',
          sets: 4,
          repsOrDuration: '6 reps',
          rpe: 8,
          tags: ['push', 'strength'],
          replacements: ['dumbbell_press', 'push_up'],
        },
        {
          id: 'weighted_pull_up',
          sets: 3,
          repsOrDuration: '6 reps',
          rpe: 8,
          tags: ['pull', 'strength'],
          replacements: ['pull_up', 'lat_pulldown'],
        },
        {
          id: 'power_clean',
          sets: 3,
          repsOrDuration: '3 reps',
          rpe: 8,
          tags: ['power', 'explosive'],
          replacements: ['kettlebell_swing', 'dumbbell_snatch'],
        },
        {
          id: 'loaded_carry_complex',
          sets: 3,
          repsOrDuration: '60 sec',
          rpe: 8,
          tags: ['carry', 'conditioning'],
          replacements: ['farmer_walk', 'suitcase_carry'],
        },
      ],
      cooldown: [
        { id: 'cool_down_walk', sets: 1, repsOrDuration: '10 min', rpe: 3 },
        { id: 'mobility_routine', sets: 1, repsOrDuration: '15 min', rpe: 2 },
      ],
    },
  ],
};
