import type { ProgramTemplate } from '../types';

export const foundational_fitness_4week: ProgramTemplate = {
  id: 'foundational_fitness_4week',
  name: 'Foundational Fitness (4-Week)',
  durationWeeks: 4,
  daysPerWeek: 3,
  description: 'Gentle introduction to fitness for beginners, office workers, and those returning to exercise. Builds movement quality, basic strength, and confidence.',
  days: [
    // WEEK 1 - Movement Introduction
    {
      week: 1,
      day: 1,
      title: 'Movement Basics',
      priority: 1,
      type: 'training',
      phase: 'Volume',
      warmup: [
        { id: 'gentle_walking', sets: 1, repsOrDuration: '5 min', rpe: 3 },
        { id: 'arm_circles_small', sets: 2, repsOrDuration: '10 each direction', rpe: 2 },
        { id: 'shoulder_rolls', sets: 2, repsOrDuration: '10 forward, 10 back', rpe: 2 },
        { id: 'gentle_neck_stretches', sets: 1, repsOrDuration: '30 sec each direction', rpe: 2 },
      ],
      exercises: [
        {
          id: 'chair_squat',
          sets: 2,
          repsOrDuration: '8-12 reps',
          rpe: 5,
          tags: ['legs', 'beginner'],
          replacements: ['bodyweight_squat', 'wall_squat'],
        },
        {
          id: 'wall_push_up',
          sets: 2,
          repsOrDuration: '8-12 reps',
          rpe: 5,
          tags: ['push', 'beginner'],
          replacements: ['incline_push_up', 'knee_push_up'],
        },
        {
          id: 'seated_row_band',
          sets: 2,
          repsOrDuration: '10-15 reps',
          rpe: 5,
          tags: ['pull', 'beginner'],
          replacements: ['resistance_band_row', 'reverse_fly'],
        },
        {
          id: 'standing_march',
          sets: 2,
          repsOrDuration: '30 sec',
          rpe: 4,
          tags: ['core', 'balance'],
          replacements: ['knee_lifts', 'heel_to_toe_walk'],
        },
        {
          id: 'calf_raises',
          sets: 2,
          repsOrDuration: '15 reps',
          rpe: 4,
          tags: ['legs', 'simple'],
          replacements: ['heel_raises', 'ankle_circles'],
        },
        {
          id: 'gentle_walking',
          sets: 1,
          repsOrDuration: '5-10 min',
          rpe: 4,
          tags: ['cardio', 'beginner'],
          replacements: ['stationary_march', 'seated_leg_extensions'],
        },
      ],
      cooldown: [
        { id: 'slow_walking', sets: 1, repsOrDuration: '3 min', rpe: 2 },
        { id: 'seated_forward_bend', sets: 1, repsOrDuration: '1 min', rpe: 2 },
        { id: 'gentle_spinal_twist', sets: 1, repsOrDuration: '30 sec each side', rpe: 2 },
        { id: 'deep_breathing', sets: 1, repsOrDuration: '2 min', rpe: 1 },
      ],
    },
    {
      week: 1,
      day: 2,
      title: 'Balance & Flexibility',
      priority: 2,
      type: 'training',
      phase: 'Volume',
      warmup: [
        { id: 'gentle_walking', sets: 1, repsOrDuration: '5 min', rpe: 3 },
        { id: 'ankle_circles', sets: 2, repsOrDuration: '10 each direction', rpe: 2 },
        { id: 'gentle_hip_circles', sets: 2, repsOrDuration: '5 each direction', rpe: 2 },
      ],
      exercises: [
        {
          id: 'single_leg_stand',
          sets: 3,
          repsOrDuration: '15-30 sec each leg',
          rpe: 5,
          tags: ['balance', 'stability'],
          replacements: ['wall_assisted_balance', 'tandem_stand'],
        },
        {
          id: 'glute_bridge_basic',
          sets: 2,
          repsOrDuration: '10-15 reps',
          rpe: 5,
          tags: ['glutes', 'beginner'],
          replacements: ['pelvic_tilts', 'supine_marching'],
        },
        {
          id: 'modified_plank_wall',
          sets: 2,
          repsOrDuration: '15-30 sec',
          rpe: 5,
          tags: ['core', 'beginner'],
          replacements: ['standing_wall_lean', 'seated_core_twist'],
        },
        {
          id: 'heel_to_toe_walk',
          sets: 2,
          repsOrDuration: '10 steps forward',
          rpe: 4,
          tags: ['balance', 'coordination'],
          replacements: ['straight_line_walk', 'side_steps'],
        },
        {
          id: 'arm_raises_light',
          sets: 2,
          repsOrDuration: '10-15 reps',
          rpe: 4,
          tags: ['shoulders', 'light'],
          replacements: ['water_bottle_lifts', 'resistance_band_pulls'],
        },
      ],
      cooldown: [
        { id: 'gentle_stretching_routine', sets: 1, repsOrDuration: '10 min', rpe: 2 },
        { id: 'relaxation_breathing', sets: 1, repsOrDuration: '5 min', rpe: 1 },
      ],
    },
    {
      week: 1,
      day: 3,
      title: 'Gentle Cardio',
      priority: 3,
      type: 'training',
      phase: 'Volume',
      warmup: [
        { id: 'slow_walking', sets: 1, repsOrDuration: '5 min', rpe: 3 },
        { id: 'gentle_arm_swings', sets: 2, repsOrDuration: '10 each direction', rpe: 2 },
      ],
      exercises: [
        {
          id: 'brisk_walking',
          sets: 3,
          repsOrDuration: '3-5 min with 1 min rest',
          rpe: 5,
          tags: ['cardio', 'walking'],
          replacements: ['stationary_bike_easy', 'seated_cardio'],
        },
        {
          id: 'step_ups_low',
          sets: 2,
          repsOrDuration: '10 each leg',
          rpe: 5,
          tags: ['legs', 'cardio'],
          replacements: ['chair_step_up', 'marching_in_place'],
        },
        {
          id: 'seated_leg_extensions',
          sets: 2,
          repsOrDuration: '12-15 reps',
          rpe: 4,
          tags: ['legs', 'seated'],
          replacements: ['ankle_pumps', 'seated_marching'],
        },
        {
          id: 'standing_side_bends',
          sets: 2,
          repsOrDuration: '10 each side',
          rpe: 4,
          tags: ['core', 'mobility'],
          replacements: ['gentle_twists', 'reach_overhead'],
        },
      ],
      cooldown: [
        { id: 'cool_down_walk', sets: 1, repsOrDuration: '5-8 min', rpe: 2 },
        { id: 'full_body_gentle_stretch', sets: 1, repsOrDuration: '8 min', rpe: 2 },
      ],
    },

    // WEEK 2 - Building Confidence
    {
      week: 2,
      day: 1,
      title: 'Strength Building',
      priority: 1,
      type: 'training',
      phase: 'Volume',
      warmup: [
        { id: 'walking', sets: 1, repsOrDuration: '5 min', rpe: 3 },
        { id: 'dynamic_arm_circles', sets: 2, repsOrDuration: '10 each direction', rpe: 3 },
        { id: 'leg_swings_gentle', sets: 2, repsOrDuration: '8 each leg', rpe: 3 },
      ],
      exercises: [
        {
          id: 'bodyweight_squat',
          sets: 3,
          repsOrDuration: '10-15 reps',
          rpe: 6,
          tags: ['legs', 'progression'],
          replacements: ['chair_squat', 'wall_squat'],
        },
        {
          id: 'incline_push_up',
          sets: 3,
          repsOrDuration: '8-12 reps',
          rpe: 6,
          tags: ['push', 'progression'],
          replacements: ['wall_push_up', 'knee_push_up'],
        },
        {
          id: 'resistance_band_row',
          sets: 3,
          repsOrDuration: '12-15 reps',
          rpe: 6,
          tags: ['pull', 'bands'],
          replacements: ['door_frame_row', 'reverse_fly'],
        },
        {
          id: 'modified_plank_knee',
          sets: 2,
          repsOrDuration: '20-40 sec',
          rpe: 6,
          tags: ['core', 'progression'],
          replacements: ['wall_plank', 'standing_core'],
        },
        {
          id: 'light_dumbbell_press',
          sets: 2,
          repsOrDuration: '12-15 reps',
          rpe: 5,
          tags: ['shoulders', 'light_weights'],
          replacements: ['water_bottle_press', 'resistance_band_press'],
        },
      ],
      cooldown: [
        { id: 'walking', sets: 1, repsOrDuration: '5 min', rpe: 3 },
        { id: 'stretching_routine', sets: 1, repsOrDuration: '8 min', rpe: 2 },
      ],
    },

    // WEEK 3 - Increased Challenge
    {
      week: 3,
      day: 1,
      title: 'Progressive Strength',
      priority: 1,
      type: 'training',
      phase: 'Strength',
      warmup: [
        { id: 'brisk_walking', sets: 1, repsOrDuration: '5 min', rpe: 4 },
        { id: 'dynamic_stretching', sets: 1, repsOrDuration: '5 min', rpe: 3 },
      ],
      exercises: [
        {
          id: 'goblet_squat_light',
          sets: 3,
          repsOrDuration: '12-15 reps',
          rpe: 6,
          tags: ['legs', 'weights'],
          replacements: ['bodyweight_squat', 'sumo_squat'],
        },
        {
          id: 'push_up_knee',
          sets: 3,
          repsOrDuration: '8-15 reps',
          rpe: 7,
          tags: ['push', 'bodyweight'],
          replacements: ['incline_push_up', 'wall_push_up'],
        },
        {
          id: 'dumbbell_row_light',
          sets: 3,
          repsOrDuration: '12-15 reps',
          rpe: 6,
          tags: ['pull', 'dumbbells'],
          replacements: ['resistance_band_row', 'single_arm_row'],
        },
        {
          id: 'plank_modified',
          sets: 3,
          repsOrDuration: '30-45 sec',
          rpe: 7,
          tags: ['core', 'isometric'],
          replacements: ['knee_plank', 'wall_plank'],
        },
        {
          id: 'walking_intervals',
          sets: 1,
          repsOrDuration: '10 min (2 min easy, 1 min brisk)',
          rpe: 6,
          tags: ['cardio', 'intervals'],
          replacements: ['steady_walking', 'stationary_bike'],
        },
      ],
      cooldown: [
        { id: 'cool_down_walk', sets: 1, repsOrDuration: '5 min', rpe: 3 },
        { id: 'flexibility_routine', sets: 1, repsOrDuration: '10 min', rpe: 2 },
      ],
    },

    // WEEK 4 - Confidence & Graduation
    {
      week: 4,
      day: 1,
      title: 'Full Body Challenge',
      priority: 1,
      type: 'training',
      phase: 'Strength',
      warmup: [
        { id: 'walking_warmup', sets: 1, repsOrDuration: '5 min', rpe: 4 },
        { id: 'full_body_mobility', sets: 1, repsOrDuration: '5 min', rpe: 3 },
      ],
      exercises: [
        {
          id: 'squat_progression',
          sets: 3,
          repsOrDuration: '15-20 reps',
          rpe: 7,
          tags: ['legs', 'bodyweight'],
          replacements: ['goblet_squat', 'sumo_squat'],
        },
        {
          id: 'push_up_full_or_knee',
          sets: 3,
          repsOrDuration: '10-15 reps',
          rpe: 7,
          tags: ['push', 'progression'],
          replacements: ['incline_push_up', 'assisted_push_up'],
        },
        {
          id: 'rowing_movement',
          sets: 3,
          repsOrDuration: '15 reps',
          rpe: 7,
          tags: ['pull', 'strength'],
          replacements: ['resistance_band_row', 'inverted_row_assisted'],
        },
        {
          id: 'core_circuit',
          sets: 2,
          repsOrDuration: '45 sec work, 15 sec rest',
          rpe: 7,
          tags: ['core', 'circuit'],
          replacements: ['individual_core_exercises', 'plank_variations'],
        },
        {
          id: 'cardio_celebration',
          sets: 1,
          repsOrDuration: '15 min varied pace',
          rpe: 6,
          tags: ['cardio', 'endurance'],
          replacements: ['walking_intervals', 'bike_intervals'],
        },
      ],
      cooldown: [
        { id: 'victory_walk', sets: 1, repsOrDuration: '8 min', rpe: 3 },
        { id: 'celebration_stretch', sets: 1, repsOrDuration: '12 min', rpe: 2 },
        { id: 'reflection_breathing', sets: 1, repsOrDuration: '3 min', rpe: 1 },
      ],
    },
  ],
};
